/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as PoliticalPartiesRouteImport } from './routes/political-parties'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticalPartiesIndexRouteImport } from './routes/political-parties.index'
import { Route as PoliticalPartiesPartyRouteImport } from './routes/political-parties.$party'

const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticalPartiesRoute = PoliticalPartiesRouteImport.update({
  id: '/political-parties',
  path: '/political-parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticalPartiesIndexRoute = PoliticalPartiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoliticalPartiesRoute,
} as any)
const PoliticalPartiesPartyRoute = PoliticalPartiesPartyRouteImport.update({
  id: '/$party',
  path: '/$party',
  getParentRoute: () => PoliticalPartiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elections': typeof ElectionsRoute
  '/political-parties': typeof PoliticalPartiesRouteWithChildren
  '/polls': typeof PollsRoute
  '/projection': typeof ProjectionRoute
  '/political-parties/$party': typeof PoliticalPartiesPartyRoute
  '/political-parties/': typeof PoliticalPartiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elections': typeof ElectionsRoute
  '/polls': typeof PollsRoute
  '/projection': typeof ProjectionRoute
  '/political-parties/$party': typeof PoliticalPartiesPartyRoute
  '/political-parties': typeof PoliticalPartiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elections': typeof ElectionsRoute
  '/political-parties': typeof PoliticalPartiesRouteWithChildren
  '/polls': typeof PollsRoute
  '/projection': typeof ProjectionRoute
  '/political-parties/$party': typeof PoliticalPartiesPartyRoute
  '/political-parties/': typeof PoliticalPartiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elections'
    | '/political-parties'
    | '/polls'
    | '/projection'
    | '/political-parties/$party'
    | '/political-parties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elections'
    | '/polls'
    | '/projection'
    | '/political-parties/$party'
    | '/political-parties'
  id:
    | '__root__'
    | '/'
    | '/elections'
    | '/political-parties'
    | '/polls'
    | '/projection'
    | '/political-parties/$party'
    | '/political-parties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElectionsRoute: typeof ElectionsRoute
  PoliticalPartiesRoute: typeof PoliticalPartiesRouteWithChildren
  PollsRoute: typeof PollsRoute
  ProjectionRoute: typeof ProjectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/political-parties': {
      id: '/political-parties'
      path: '/political-parties'
      fullPath: '/political-parties'
      preLoaderRoute: typeof PoliticalPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/political-parties/': {
      id: '/political-parties/'
      path: '/'
      fullPath: '/political-parties/'
      preLoaderRoute: typeof PoliticalPartiesIndexRouteImport
      parentRoute: typeof PoliticalPartiesRoute
    }
    '/political-parties/$party': {
      id: '/political-parties/$party'
      path: '/$party'
      fullPath: '/political-parties/$party'
      preLoaderRoute: typeof PoliticalPartiesPartyRouteImport
      parentRoute: typeof PoliticalPartiesRoute
    }
  }
}

interface PoliticalPartiesRouteChildren {
  PoliticalPartiesPartyRoute: typeof PoliticalPartiesPartyRoute
  PoliticalPartiesIndexRoute: typeof PoliticalPartiesIndexRoute
}

const PoliticalPartiesRouteChildren: PoliticalPartiesRouteChildren = {
  PoliticalPartiesPartyRoute: PoliticalPartiesPartyRoute,
  PoliticalPartiesIndexRoute: PoliticalPartiesIndexRoute,
}

const PoliticalPartiesRouteWithChildren =
  PoliticalPartiesRoute._addFileChildren(PoliticalPartiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElectionsRoute: ElectionsRoute,
  PoliticalPartiesRoute: PoliticalPartiesRouteWithChildren,
  PollsRoute: PollsRoute,
  ProjectionRoute: ProjectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
