import type { Country, ElectionResult, FullParty, Institute, Poll } from "./types";

// =====================================================================
// SYNTHETIC DEMO DATA — UK only.
// Party names and historical election outlines are real; poll percentages
// are generated by the seeder for demonstration purposes.
// =====================================================================

/** "As of" date — today's date, drives weighted-recency math + timestamp shown in the UI. */
export const AS_OF = new Date().toISOString().slice(0, 10);

export const country: Country = {
  code: "united-kingdom",
  name: "United Kingdom",
  flag: "🇬🇧",
  system: "First-past-the-post, single-member constituencies",
  parliamentSize: 650,
  majorityThreshold: 326,
  electoralThreshold: 0,
  nextElection: "2029-05-03",
  memberships: ["NATO", "G7", "G20", "OECD", "Council of Europe", "Commonwealth"],
  systemBlurb:
    "650 single-member constituencies elect MPs by simple plurality. There is no national threshold; geographic concentration determines representation, which historically rewards two-bloc politics and penalises evenly-spread third parties.",
  formationBlurb:
    "The monarch invites the leader most likely to command Commons confidence to form a government. Single-party majorities are the norm; formal coalitions are rare and minority governments rely on confidence-and-supply arrangements.",
  democracyScore: 81,
  democracyTrend: [86, 85, 84, 84, 83, 82, 81, 81, 80, 81],
  governmentType: "Parliamentary constitutional monarchy",
  turnoutTrend: [66.1, 68.8, 67.3, 59.7],
  governingParties: ["labour"],
  headOfGovernment: {
    name: "Sir Keir Starmer",
    title: "Prime Minister",
    partyId: "labour",
    since: "2024-07-05",
    resignedDate: "2026-06-22",
  },
};

// Convenience alias to keep older imports working.
export const countries: Country[] = [country];

/* -------------------------------------------------------------------- */
/* Parties — active + historical                                        */
/* -------------------------------------------------------------------- */

export const parties: FullParty[] = [
  // ------- Active, in poll breakdown --------------------------------
  {
    id: "labour",
    countryCode: "united-kingdom",
    name: "Labour",
    abbr: "LAB",
    color: "#E4003B",
    bloc: "centerleft",
    euStance: "Neutral",
    leader: "Sir Keir Starmer",
    description:
      "Social-democratic party currently in government with a large Commons majority. Centred on public-service investment, a closer relationship with the EU short of rejoining, and incremental constitutional reform.",
    compassX: -3.5,
    compassY: -2.5,
    euStanceScore: 3,
    policy: {
      "Economy & State": 38,
      "Society & Values": 28,
      "Environment & Climate": 32,
      "Migration & Integration": 42,
      "Democracy & Institutions": 35,
    },
    policyPrev: { "Economy & State": 32, "Migration & Integration": 36 },
    spectrumLabel: "Centre-Left",
    euGroup: "S&D (associate, post-Brexit)",
    targetVoter:
      "Urban professionals, public-sector workers, younger graduates, multi-ethnic city seats.",
    inPolls: true,
    govShareLifetime: 31,
    historicResults: [
      { year: 2024, pct: 33.7, seats: 411 },
      { year: 2019, pct: 32.1, seats: 202 },
      { year: 2017, pct: 40.0, seats: 262 },
      { year: 2015, pct: 30.4, seats: 232 },
      { year: 2010, pct: 29.0, seats: 258 },
      { year: 2005, pct: 35.2, seats: 355 },
    ],
  },
  {
    id: "conservative",
    countryCode: "united-kingdom",
    name: "Conservative Party",
    abbr: "CON",
    color: "#0087DC",
    bloc: "centerright",
    euStance: "Anti-EU",
    leader: "Robert Birchall",
    description:
      "Historic centre-right party in opposition after the 2024 defeat. Currently balancing a free-market wing with a national-conservative wing in the wake of Reform's rise.",
    compassX: 4.5,
    compassY: 5.0,
    euStanceScore: -4,
    policy: {
      "Economy & State": 72,
      "Society & Values": 65,
      "Environment & Climate": 58,
      "Migration & Integration": 70,
      "Democracy & Institutions": 62,
    },
    policyPrev: { "Migration & Integration": 60, "Environment & Climate": 50 },
    spectrumLabel: "Centre-Right",
    euGroup: "ECR (former)",
    targetVoter:
      "Older homeowners, shire and small-town England, business owners, traditional 'small-c' conservatives.",
    inPolls: true,
    govShareLifetime: 56,
    historicResults: [
      { year: 2024, pct: 23.7, seats: 121 },
      { year: 2019, pct: 43.6, seats: 365 },
      { year: 2017, pct: 42.4, seats: 317 },
      { year: 2015, pct: 36.9, seats: 330 },
      { year: 2010, pct: 36.1, seats: 306 },
      { year: 2005, pct: 32.4, seats: 198 },
    ],
  },
  {
    id: "reform-uk",
    countryCode: "united-kingdom",
    name: "Reform UK",
    abbr: "REF",
    color: "#12B6CF",
    bloc: "farright",
    euStance: "Anti-EU",
    leader: "Nigel Farrant",
    description:
      "National-populist insurgent party, the successor of the Brexit Party, currently squeezing the Conservative vote in England and topping several headline polls.",
    compassX: 5.5,
    compassY: 7.5,
    euStanceScore: -9,
    policy: {
      "Economy & State": 70,
      "Society & Values": 82,
      "Environment & Climate": 78,
      "Migration & Integration": 92,
      "Democracy & Institutions": 70,
    },
    spectrumLabel: "Right-wing populist",
    euGroup: "PfE (sympathetic)",
    targetVoter: "Post-industrial towns, non-graduate older voters, Leave-leaning communities.",
    inPolls: true,
    govShareLifetime: 0,
    historicResults: [
      { year: 2024, pct: 14.3, seats: 5 },
      { year: 2019, pct: 2.0, seats: 0 },
    ],
  },
  {
    id: "liberal-democrats",
    countryCode: "united-kingdom",
    name: "Liberal Democrats",
    abbr: "LD",
    color: "#FAA61A",
    bloc: "liberal",
    euStance: "Pro-EU",
    leader: "Sir Ed Davison",
    description:
      "Centrist liberal party with a southern-English suburban base. Strongly pro-European, civil-libertarian, focused on local services and constitutional reform.",
    compassX: 0,
    compassY: -3,
    euStanceScore: 9,
    policy: {
      "Economy & State": 48,
      "Society & Values": 22,
      "Environment & Climate": 25,
      "Migration & Integration": 30,
      "Democracy & Institutions": 18,
    },
    spectrumLabel: "Centre / Liberal",
    categoryTag: "Liberal",
    euGroup: "Renew Europe (associate)",
    targetVoter:
      "Affluent suburban professionals, Remain-leaning seats in the South-West and Home Counties.",
    inPolls: true,
    govShareLifetime: 5,
    historicResults: [
      { year: 2024, pct: 12.2, seats: 72 },
      { year: 2019, pct: 11.6, seats: 11 },
      { year: 2017, pct: 7.4, seats: 12 },
      { year: 2015, pct: 7.9, seats: 8 },
      { year: 2010, pct: 23.0, seats: 57 },
    ],
  },
  {
    id: "green-party",
    countryCode: "united-kingdom",
    name: "Green Party of England & Wales",
    abbr: "GRN",
    color: "#6AB023",
    bloc: "green",
    euStance: "Pro-EU",
    leader: "Carla Ramsay",
    description:
      "Eco-socialist party with rising urban and student support. Climate action and wealth redistribution are the twin pillars of the platform.",
    compassX: -5,
    compassY: -6,
    euStanceScore: 8,
    policy: {
      "Economy & State": 22,
      "Society & Values": 15,
      "Environment & Climate": 8,
      "Migration & Integration": 22,
      "Democracy & Institutions": 20,
    },
    spectrumLabel: "Left-liberal environmentalist",
    categoryTag: "Green",
    euGroup: "Greens/EFA (associate)",
    targetVoter: "University towns, climate-conscious younger voters, urban renters.",
    inPolls: true,
    govShareLifetime: 0,
    historicResults: [
      { year: 2024, pct: 6.7, seats: 4 },
      { year: 2019, pct: 2.7, seats: 1 },
      { year: 2017, pct: 1.6, seats: 1 },
      { year: 2015, pct: 3.8, seats: 1 },
    ],
  },
  {
    id: "snp",
    countryCode: "united-kingdom",
    name: "Scottish National Party",
    abbr: "SNP",
    color: "#ECC510",
    bloc: "regional",
    euStance: "Pro-EU",
    leader: "John Swinney",
    description:
      "Centre-left party advocating Scottish independence and re-entry to the EU. Dominant force in Holyrood politics for the past decade.",
    compassX: -3,
    compassY: -0.5,
    euStanceScore: 9,
    policy: {
      "Economy & State": 42,
      "Society & Values": 25,
      "Environment & Climate": 30,
      "Migration & Integration": 28,
      "Democracy & Institutions": 30,
    },
    spectrumLabel: "Centre-left regional",
    categoryTag: "Regional",
    euGroup: "Greens/EFA (associate)",
    targetVoter: "Pro-independence Scottish voters across the political centre and left.",
    inPolls: true,
    govShareLifetime: 0,
    historicResults: [
      { year: 2024, pct: 2.5, seats: 9 },
      { year: 2019, pct: 3.9, seats: 48 },
      { year: 2017, pct: 3.0, seats: 35 },
      { year: 2015, pct: 4.7, seats: 56 },
    ],
  },
  {
    id: "plaid-cymru",
    countryCode: "united-kingdom",
    name: "Plaid Cymru",
    abbr: "PC",
    color: "#005B54",
    bloc: "regional",
    euStance: "Pro-EU",
    leader: "Rhun ap Iorwerth",
    description:
      "Welsh nationalist, centre-left party. Pro-independence for Wales, pro-EU, with a strong cultural and linguistic agenda.",
    compassX: -4.5,
    compassY: -1.0,
    euStanceScore: 8,
    policy: {
      "Economy & State": 38,
      "Society & Values": 25,
      "Environment & Climate": 26,
      "Migration & Integration": 28,
      "Democracy & Institutions": 28,
    },
    spectrumLabel: "Centre-left Welsh nationalist",
    categoryTag: "Regional",
    euGroup: "Greens/EFA (associate)",
    targetVoter:
      "Welsh-speaking communities, rural North and West Wales, civic Welsh nationalists.",
    inPolls: true,
    govShareLifetime: 0,
    historicResults: [
      { year: 2024, pct: 0.7, seats: 4 },
      { year: 2019, pct: 0.5, seats: 4 },
    ],
  },
  {
    id: "others",
    countryCode: "united-kingdom",
    name: "Others",
    abbr: "OTH",
    bloc: "other",
    euStance: "Neutral",
    leader: "—",
    description:
      "Combined share for parties below the topline threshold (Workers Party, Reclaim, Alliance, smaller regional and protest parties).",
    compassX: 0,
    compassY: 0,
    euStanceScore: 0,
    policy: {
      "Economy & State": 50,
      "Society & Values": 50,
      "Environment & Climate": 50,
      "Migration & Integration": 50,
      "Democracy & Institutions": 50,
    },
    spectrumLabel: "Mixed",
    euGroup: "—",
    targetVoter: "Heterogenous protest, regional and single-issue support.",
    inPolls: true,
  },

  // ------- Active, off-topline -------------------------------------
  {
    id: "dup",
    countryCode: "united-kingdom",
    name: "Democratic Unionist Party",
    abbr: "DUP",
    color: "#D46A4C",
    bloc: "right",
    euStance: "Anti-EU",
    leader: "Gavin Robinson",
    description:
      "Northern Irish unionist, socially conservative party. Pro-Union, sceptical of the Windsor Framework, evangelical-Protestant roots.",
    compassX: 4,
    compassY: 7,
    euStanceScore: -7,
    policy: {
      "Economy & State": 60,
      "Society & Values": 78,
      "Environment & Climate": 65,
      "Migration & Integration": 72,
      "Democracy & Institutions": 55,
    },
    spectrumLabel: "Right-wing unionist",
    categoryTag: "Regional",
    euGroup: "ECR (former)",
    targetVoter: "Protestant unionist communities in Northern Ireland.",
  },
  {
    id: "sinn-fein",
    countryCode: "united-kingdom",
    name: "Sinn Féin",
    abbr: "SF",
    color: "#326760",
    bloc: "left",
    euStance: "Pro-EU",
    leader: "Mary Lou McDonald",
    description:
      "Irish republican, left-wing party, advocating Irish reunification. MPs do not take their Commons seats by long-standing abstentionist policy.",
    compassX: -4,
    compassY: -4,
    euStanceScore: 7,
    policy: {
      "Economy & State": 28,
      "Society & Values": 30,
      "Environment & Climate": 28,
      "Migration & Integration": 32,
      "Democracy & Institutions": 30,
    },
    spectrumLabel: "Left-wing Irish republican",
    categoryTag: "Regional",
    euGroup: "The Left (associate)",
    targetVoter: "Nationalist and republican communities in Northern Ireland.",
  },
  {
    id: "sdlp",
    countryCode: "united-kingdom",
    name: "Social Democratic & Labour Party",
    abbr: "SDLP",
    color: "#2AA82C",
    bloc: "centerleft",
    euStance: "Pro-EU",
    leader: "Claire Hanna",
    description:
      "Moderate Irish nationalist, centre-left party. Pro-EU, socially progressive, takes its Commons seats.",
    compassX: -2,
    compassY: -2,
    euStanceScore: 8,
    policy: {
      "Economy & State": 38,
      "Society & Values": 28,
      "Environment & Climate": 30,
      "Migration & Integration": 30,
      "Democracy & Institutions": 30,
    },
    spectrumLabel: "Centre-left nationalist",
    categoryTag: "Regional",
    euGroup: "S&D (associate)",
    targetVoter: "Moderate nationalist voters in Northern Ireland.",
  },
  {
    id: "alliance",
    countryCode: "united-kingdom",
    name: "Alliance Party of Northern Ireland",
    abbr: "APNI",
    color: "#F6CB2F",
    bloc: "liberal",
    euStance: "Pro-EU",
    leader: "Naomi Long",
    description:
      "Cross-community liberal party rejecting the unionist/nationalist binary. Centrist, pro-EU, civil-libertarian.",
    compassX: 0,
    compassY: -2,
    euStanceScore: 8,
    policy: {
      "Economy & State": 50,
      "Society & Values": 25,
      "Environment & Climate": 28,
      "Migration & Integration": 30,
      "Democracy & Institutions": 22,
    },
    spectrumLabel: "Liberal cross-community",
    categoryTag: "Liberal",
    euGroup: "Renew Europe (associate)",
    targetVoter: "Younger, urban, non-aligned Northern Irish voters.",
  },
  {
    id: "restore-britain",
    countryCode: "united-kingdom",
    name: "Restore Britain",
    abbr: "RST",
    color: "#1a1a6e",
    bloc: "farright",
    euStance: "Anti-EU",
    leader: "L. Anderson",
    description:
      "Nationalist breakaway party of former Conservative and Reform figures. Hard-immigration line, traditionalist social policy.",
    compassX: 6,
    compassY: 8,
    euStanceScore: -9,
    policy: {
      "Economy & State": 65,
      "Society & Values": 88,
      "Environment & Climate": 82,
      "Migration & Integration": 95,
      "Democracy & Institutions": 70,
    },
    spectrumLabel: "Hard-right nationalist",
    euGroup: "No affiliated group",
    targetVoter: "Voters to the right of Reform — committed nationalist activists.",
  },
  {
    id: "workers-party",
    countryCode: "united-kingdom",
    name: "Workers Party of Britain",
    abbr: "WPB",
    color: "#8B0000",
    bloc: "left",
    euStance: "Neutral",
    leader: "George Galloway",
    description:
      "Left-populist, socially conservative, anti-NATO party. Mixes economic-left positions with traditionalist cultural stances.",
    compassX: -4,
    compassY: 4,
    euStanceScore: -2,
    policy: {
      "Economy & State": 22,
      "Society & Values": 65,
      "Environment & Climate": 45,
      "Migration & Integration": 60,
      "Democracy & Institutions": 50,
    },
    spectrumLabel: "Left-populist",
    euGroup: "No affiliated group",
    targetVoter: "Working-class voters with strong views on Palestine and economic redistribution.",
  },
  {
    id: "animal-welfare",
    countryCode: "united-kingdom",
    name: "Animal Welfare Party",
    abbr: "AWP",
    color: "#4CAF50",
    bloc: "green",
    euStance: "Pro-EU",
    leader: "Vanessa Hudson",
    description:
      "Single-issue ecologist party focused on animal rights, plant-based food systems and sentience legislation.",
    compassX: -3,
    compassY: -3,
    euStanceScore: 7,
    policy: {
      "Economy & State": 40,
      "Society & Values": 20,
      "Environment & Climate": 5,
      "Migration & Integration": 30,
      "Democracy & Institutions": 28,
    },
    spectrumLabel: "Single-issue ecologist",
    categoryTag: "Animal Welfare",
    euGroup: "Greens/EFA (associate)",
    targetVoter: "Animal-rights activists, plant-based and vegan communities.",
  },

  // ------- Historical / defunct ------------------------------------
  {
    id: "ukip",
    countryCode: "united-kingdom",
    name: "UK Independence Party",
    abbr: "UKIP",
    color: "#70147A",
    bloc: "farright",
    euStance: "Anti-EU",
    leader: "Nick Tenconi",
    description:
      "Eurosceptic, right-wing populist party that drove the 1992–2016 anti-EU campaign. Largely supplanted by the Brexit Party and Reform UK after 2017.",
    compassX: 5,
    compassY: 7,
    euStanceScore: -10,
    policy: {
      "Economy & State": 65,
      "Society & Values": 80,
      "Environment & Climate": 80,
      "Migration & Integration": 92,
      "Democracy & Institutions": 68,
    },
    spectrumLabel: "Right-wing populist (defunct)",
    euGroup: "EFDD (former)",
    targetVoter: "Older, white, non-graduate Leave voters before 2017.",
    historical: true,
    historicResults: [
      { year: 2015, pct: 12.6, seats: 1 },
      { year: 2010, pct: 3.1, seats: 0 },
    ],
  },
  {
    id: "liberal-party",
    countryCode: "united-kingdom",
    name: "Liberal Party (historical)",
    abbr: "LIB",
    color: "#FAA61A",
    bloc: "liberal",
    euStance: "Pro-EU",
    leader: "—",
    description:
      "Major 19th- and early-20th-century governing party. Merged with the SDP in 1988 to form the Liberal Democrats.",
    compassX: 0,
    compassY: -2,
    euStanceScore: 7,
    policy: {
      "Economy & State": 45,
      "Society & Values": 30,
      "Environment & Climate": 50,
      "Migration & Integration": 40,
      "Democracy & Institutions": 25,
    },
    spectrumLabel: "Liberal (historical)",
    categoryTag: "Liberal",
    euGroup: "—",
    targetVoter: "Nonconformist middle classes, free-trade industrialists.",
    historical: true,
    govShareLifetime: 26,
  },
  {
    id: "sdp",
    countryCode: "united-kingdom",
    name: "Social Democratic Party (1981)",
    abbr: "SDP",
    bloc: "centerleft",
    euStance: "Pro-EU",
    leader: "—",
    description:
      "Centrist breakaway from Labour formed in 1981 by the 'Gang of Four'. Merged with the Liberal Party in 1988.",
    compassX: -1,
    compassY: -1,
    euStanceScore: 8,
    policy: {
      "Economy & State": 45,
      "Society & Values": 30,
      "Environment & Climate": 45,
      "Migration & Integration": 35,
      "Democracy & Institutions": 25,
    },
    spectrumLabel: "Centrist (defunct)",
    euGroup: "—",
    targetVoter: "Moderate ex-Labour voters of the 1980s.",
    historical: true,
  },
  {
    id: "communist-party",
    countryCode: "united-kingdom",
    name: "Communist Party of Britain",
    abbr: "CPB",
    bloc: "farleft",
    euStance: "Anti-EU",
    leader: "—",
    description:
      "Marxist–Leninist party, successor to the historic CPGB tradition. No Westminster representation.",
    compassX: -8,
    compassY: -3,
    euStanceScore: -4,
    policy: {
      "Economy & State": 8,
      "Society & Values": 30,
      "Environment & Climate": 25,
      "Migration & Integration": 25,
      "Democracy & Institutions": 30,
    },
    spectrumLabel: "Marxist–Leninist",
    euGroup: "—",
    targetVoter: "Marxist activists, trade-union militants.",
    historical: true,
  },
  {
    id: "ulster-unionist",
    countryCode: "united-kingdom",
    name: "Ulster Unionist Party",
    abbr: "UUP",
    color: "#48A5EE",
    bloc: "centerright",
    euStance: "Anti-EU",
    leader: "Mike Nesbitt",
    description:
      "Once-dominant unionist party of Northern Ireland; supplanted by the DUP after 2003 but still active.",
    compassX: 3,
    compassY: 5,
    euStanceScore: -3,
    policy: {
      "Economy & State": 60,
      "Society & Values": 65,
      "Environment & Climate": 60,
      "Migration & Integration": 60,
      "Democracy & Institutions": 50,
    },
    spectrumLabel: "Centre-right unionist",
    categoryTag: "Regional",
    euGroup: "—",
    targetVoter: "Moderate unionist voters in Northern Ireland.",
    historical: true,
  },
];

/* -------------------------------------------------------------------- */
/* Institutes                                                           */
/* -------------------------------------------------------------------- */

export const institutes: Institute[] = [
  { id: "yougov", countryCode: "united-kingdom", name: "YouGov", reliability: 88 },
  { id: "opinium", countryCode: "united-kingdom", name: "Opinium", reliability: 84 },
  { id: "ipsos", countryCode: "united-kingdom", name: "Ipsos", reliability: 86 },
  { id: "moreincommon", countryCode: "united-kingdom", name: "More in Common", reliability: 80 },
  { id: "deltapoll", countryCode: "united-kingdom", name: "Deltapoll", reliability: 78 },
  { id: "findoutnow", countryCode: "united-kingdom", name: "Find Out Now", reliability: 76 },
  { id: "savanta", countryCode: "united-kingdom", name: "Savanta", reliability: 79 },
  { id: "redfield", countryCode: "united-kingdom", name: "Redfield & Wilton", reliability: 74 },
  { id: "techne", countryCode: "united-kingdom", name: "Techne UK", reliability: 70 },
  { id: "people-polling", countryCode: "united-kingdom", name: "People Polling", reliability: 68 },
];

/* -------------------------------------------------------------------- */
/* Poll generator (UK only)                                             */
/* -------------------------------------------------------------------- */

/** Centre-of-mass per party (in %). Polls jitter around this and drift slowly. */
const center: Record<string, number> = {
  "reform-uk": 26.0,
  labour: 24.0,
  conservative: 20.0,
  "liberal-democrats": 13.0,
  "green-party": 8.0,
  snp: 2.6,
  "plaid-cymru": 0.7,
  others: 5.7,
};

/** Net drift from a year ago to today (towards "now"). */
const drift: Record<string, number> = {
  "reform-uk": +6.0,
  labour: -7.0,
  conservative: -2.5,
  "liberal-democrats": +0.5,
  "green-party": +1.5,
  snp: -0.5,
  "plaid-cymru": 0,
  others: +2.0,
};

function mulberry32(seed: number) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function generatePolls(): Poll[] {
  const rng = mulberry32(20260621);
  const out: Poll[] = [];
  const today = new Date(AS_OF);
  const polledIds = Object.keys(center);
  let idx = 0;
  // 40 polls across ~12 months, cycling through institutes
  for (let i = 0; i < 40; i++) {
    const inst = institutes[i % institutes.length];
    const daysAgo = Math.floor(i * 9 + rng() * 5);
    const fieldworkEnd = new Date(today);
    fieldworkEnd.setDate(fieldworkEnd.getDate() - daysAgo);
    const publishDate = new Date(fieldworkEnd);
    publishDate.setDate(publishDate.getDate() + 2);
    const phase = 1 - i / 40; // 1 = today, 0 = oldest
    const raw: Record<string, number> = {};
    let sum = 0;
    for (const id of polledIds) {
      const noise = (rng() - 0.5) * 2.6;
      const val = Math.max(0.3, center[id] + drift[id] * phase + noise - drift[id] * 0.5);
      raw[id] = val;
      sum += val;
    }
    const norm: Record<string, number> = {};
    for (const k of Object.keys(raw)) norm[k] = +((raw[k] * 100) / sum).toFixed(1);
    out.push({
      id: `uk-poll-${++idx}`,
      countryCode: "united-kingdom",
      instituteId: inst.id,
      fieldworkEnd: fieldworkEnd.toISOString().slice(0, 10),
      publishDate: publishDate.toISOString().slice(0, 10),
      sampleSize: 1000 + Math.floor(rng() * 1400),
      electionType: "national",
      results: norm,
    });
  }
  return out.sort((a, b) => b.fieldworkEnd.localeCompare(a.fieldworkEnd));
}

export const polls: Poll[] = generatePolls();

/* -------------------------------------------------------------------- */
/* Elections                                                            */
/* -------------------------------------------------------------------- */

export const elections: Record<string, ElectionResult[]> = {
  "united-kingdom": [
    {
      date: "2024-07-04",
      type: "national",
      turnout: 59.7,
      results: [
        { partyId: "labour", pct: 33.7, seats: 411 },
        { partyId: "conservative", pct: 23.7, seats: 121 },
        { partyId: "reform-uk", pct: 14.3, seats: 5 },
        { partyId: "liberal-democrats", pct: 12.2, seats: 72 },
        { partyId: "green-party", pct: 6.7, seats: 4 },
        { partyId: "snp", pct: 2.5, seats: 9 },
        { partyId: "plaid-cymru", pct: 0.7, seats: 4 },
        { partyId: "others", pct: 6.2, seats: 24 },
      ],
      coalitionFormed: ["labour"],
    },
    {
      date: "2019-12-12",
      type: "national",
      turnout: 67.3,
      results: [
        { partyId: "conservative", pct: 43.6, seats: 365 },
        { partyId: "labour", pct: 32.1, seats: 202 },
        { partyId: "liberal-democrats", pct: 11.6, seats: 11 },
        { partyId: "snp", pct: 3.9, seats: 48 },
        { partyId: "green-party", pct: 2.7, seats: 1 },
        { partyId: "reform-uk", pct: 2.0, seats: 0 },
        { partyId: "plaid-cymru", pct: 0.5, seats: 4 },
        { partyId: "others", pct: 3.6, seats: 19 },
      ],
      coalitionFormed: ["conservative"],
    },
    {
      date: "2017-06-08",
      type: "national",
      turnout: 68.8,
      results: [
        { partyId: "conservative", pct: 42.4, seats: 317 },
        { partyId: "labour", pct: 40.0, seats: 262 },
        { partyId: "liberal-democrats", pct: 7.4, seats: 12 },
        { partyId: "snp", pct: 3.0, seats: 35 },
        { partyId: "green-party", pct: 1.6, seats: 1 },
        { partyId: "plaid-cymru", pct: 0.5, seats: 4 },
        { partyId: "others", pct: 5.1, seats: 19 },
      ],
      coalitionFormed: ["conservative", "dup"],
    },
  ],
};

/* -------------------------------------------------------------------- */
/* Helpers                                                              */
/* -------------------------------------------------------------------- */

export function partiesByCountry(_code?: string) {
  return parties.filter((p) => p.countryCode === "united-kingdom");
}
export function activeParties() {
  return parties.filter((p) => !p.historical);
}
export function historicalParties() {
  return parties.filter((p) => p.historical);
}
export function polledParties() {
  return parties.filter((p) => p.inPolls);
}
export function institutesByCountry(_code?: string) {
  return institutes;
}
export function pollsByCountry(_code?: string) {
  return polls;
}
export function countryByCode(_code?: string) {
  return country;
}
export function partyById(id: string) {
  return parties.find((p) => p.id === id);
}
export function instituteById(id: string) {
  return institutes.find((i) => i.id === id);
}
